#!/bin/bash

# Automatic Index Generator for DSA Java Project
# Scans Java files and generates docs/INDEX.md

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DOCS_DIR="$PROJECT_ROOT/docs"
INDEX_FILE="$DOCS_DIR/INDEX.md"
SOURCE_DIR="$PROJECT_ROOT"

# Algorithm categories and patterns
declare -A ALGORITHM_CATEGORIES=(
    ["search"]="BinarySearch LinearSearch LinearSearchWithFrequency"
    ["sorting"]="BubbleSort InsertionSort SelectionSort QuickSortAlgorithm MergeSortAlgorithm"
    ["datastructures"]="LinkedListWithAddresses SinglyLinkedList StackOperations LinearQueue CircularQueue PriorityQueueOperations QueueUsingArray DequeOperations"
    ["arrays"]="InsertElement RemoveElement Traversal MatrxMultiplication SparseMatrix"
    ["statistical"]="SecondSmallestSecondLargest SmallestLargest"
    ["utility"]="TestFramework TestLinkedList sample"
)

# Category descriptions
declare -A CATEGORY_DESCRIPTIONS=(
    ["search"]="🔍 Search Algorithms"
    ["sorting"]="📊 Sorting Algorithms"
    ["datastructures"]="🔗 Data Structures"
    ["arrays"]="🔢 Array Operations"
    ["statistical"]="📈 Statistical Analysis"
    ["utility"]="🛠️ Utility Classes"
)

# Function to convert filename to display name
convert_filename_to_name() {
    local filename="$1"
    # Remove .java extension
    local basename="${filename%.java}"
    # Convert CamelCase to Space Case
    echo "$basename" | sed -E 's/([a-z])([A-Z])/\1 \2/g'
}

# Function to categorize algorithm
categorize_algorithm() {
    local filename="$1"
    local basename="${filename%.java}"
    
    for category in "${!ALGORITHM_CATEGORIES[@]}"; do
        local algorithms="${ALGORITHM_CATEGORIES[$category]}"
        if [[ " $algorithms " =~ " $basename " ]]; then
            echo "$category"
            return
        fi
    done
    
    # Default category
    echo "other"
}

# Function to check if file is a test file
is_test_file() {
    local filename="$1"
    [[ "$filename" == *"_Test.java" ]]
}

# Function to check if file is a documentation file
is_documentation_file() {
    local filename="$1"
    [[ "$filename" == *"_Documentation.md" ]]
}

# Function to check if file should be excluded
should_exclude_file() {
    local filename="$1"
    local basename="${filename%.java}"
    
    # Exclude test files
    if is_test_file "$filename"; then
        return 0
    fi
    
    # Exclude documentation files
    if is_documentation_file "$filename"; then
        return 0
    fi
    
    # Exclude specific utility files if needed
    local exclude_patterns="TestFramework sample"
    if [[ " $exclude_patterns " =~ " $basename " ]]; then
        return 0
    fi
    
    return 1
}

# Function to find all algorithm files
find_algorithm_files() {
    local source_dir="$1"
    
    log_info "Scanning for algorithm files in: $source_dir"
    
    # Find all .java files and filter
    find "$source_dir" -maxdepth 1 -name "*.java" -type f | while read -r file; do
        local filename=$(basename "$file")
        
        if ! should_exclude_file "$filename"; then
            echo "$filename"
        fi
    done | sort
}

# Function to generate index content
generate_index_content() {
    local algorithm_files=("$@")
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    
    # Start building content
    cat << EOF
# DSA Java - Algorithm Index

> 🎯 **Comprehensive index of all Data Structures and Algorithms implementations**

---

📅 **Last Updated**: $timestamp  
🔧 **Auto-generated by**: \`scripts/generate-index.sh\`  
📊 **Total Algorithms**: ${#algorithm_files[@]}

---

## 📚 Algorithm Categories

EOF

    # Group algorithms by category
    declare -A categorized_files
    declare -A uncategorized_files
    
    # Categorize each algorithm
    for file in "${algorithm_files[@]}"; do
        local category=$(categorize_algorithm "$file")
        if [[ "$category" == "other" ]]; then
            uncategorized_files["$file"]=1
        else
            categorized_files["$category"]+="$file "
        fi
    done
    
    # Generate sections for each category
    for category in "${!ALGORITHM_CATEGORIES[@]}"; do
        local description="${CATEGORY_DESCRIPTIONS[$category]}"
        local files="${categorized_files[$category]}"
        
        if [[ -n "$files" ]]; then
            echo "### $description"
            echo ""
            
            # Sort files alphabetically
            local sorted_files=($(echo $files | tr ' ' '\n' | sort))
            
            for file in "${sorted_files[@]}"; do
                local display_name=$(convert_filename_to_name "$file")
                local doc_file="${file%.java}_Documentation.md"
                local test_file="${file%.java}_Test.java"
                local test_doc_file="${file%.java}_Test_Documentation.md"
                
                # Check if documentation and test files exist
                local doc_exists="❌"
                local test_exists="❌"
                local test_doc_exists="❌"
                
                if [[ -f "$DOCS_DIR/algorithms/$doc_file" ]] || [[ -f "$DOCS_DIR/$doc_file" ]]; then
                    doc_exists="✅"
                fi
                
                if [[ -f "$test_file" ]]; then
                    test_exists="✅"
                fi
                
                if [[ -f "$DOCS_DIR/testing/$test_doc_file" ]] || [[ -f "$DOCS_DIR/$test_doc_file" ]]; then
                    test_doc_exists="✅"
                fi
                
                echo "- **[$display_name]($file)**"
                echo "  - 📄 Algorithm: $doc_exists Documentation"
                echo "  - 🧪 Test: $test_exists Implementation"
                echo "  - 📋 Test Docs: $test_doc_exists Documentation"
                echo ""
            done
        fi
    done
    
    # Handle uncategorized files
    if [[ ${#uncategorized_files[@]} -gt 0 ]]; then
        echo "### 🛠️ Other Algorithms"
        echo ""
        
        for file in "${!uncategorized_files[@]}"; do
            local display_name=$(convert_filename_to_name "$file")
            echo "- **[$display_name]($file)**"
            echo ""
        done
    fi
    
    # Add statistics section
    cat << EOF

---

## 📊 Algorithm Statistics

### By Category
EOF

    # Generate statistics
    for category in "${!ALGORITHM_CATEGORIES[@]}"; do
        local files="${categorized_files[$category]}"
        local count=0
        
        if [[ -n "$files" ]]; then
            count=$(echo $files | wc -w)
        fi
        
        local description="${CATEGORY_DESCRIPTIONS[$category]}"
        echo "- **$description**: $count algorithms"
    done
    
    if [[ ${#uncategorized_files[@]} -gt 0 ]]; then
        echo "- **🛠️ Other Algorithms**: ${#uncategorized_files[@]} algorithms"
    fi
    
    cat << EOF

### Documentation Coverage
EOF
    
    # Calculate documentation coverage
    local total_algorithms=${#algorithm_files[@]}
    local documented_algorithms=0
    local tested_algorithms=0
    
    for file in "${algorithm_files[@]}"; do
        local doc_file="${file%.java}_Documentation.md"
        local test_file="${file%.java}_Test.java"
        
        if [[ -f "$DOCS_DIR/algorithms/$doc_file" ]] || [[ -f "$DOCS_DIR/$doc_file" ]]; then
            ((documented_algorithms++))
        fi
        
        if [[ -f "$test_file" ]]; then
            ((tested_algorithms++))
        fi
    done
    
    local doc_coverage=$((documented_algorithms * 100 / total_algorithms))
    local test_coverage=$((tested_algorithms * 100 / total_algorithms))
    
    echo "- **Documentation Coverage**: $doc_coverage% ($documented_algorithms/$total_algorithms)"
    echo "- **Test Coverage**: $test_coverage% ($tested_algorithms/$total_algorithms)"
    
    cat << EOF

---

## 🔧 Development Commands

### Index Generation
\`\`\`bash
# Regenerate this index
./scripts/generate-index.sh

# Check if index is up to date
./scripts/check-index.sh
\`\`\`

### Algorithm Development
\`\`\`bash
# Run all algorithms
./gradlew runAllAlgorithms

# Run all tests
./gradlew test

# Generate documentation
./gradlew generateDocsIndex
\`\`\`

---

## 📚 Quick Reference

### Algorithm Complexity
| Category | Best | Average | Worst |
|----------|-------|----------|--------|
| **Search** | O(1) | O(log n) | O(n) |
| **Sorting** | O(n) | O(n log n) | O(n²) |
| **Data Structures** | O(1) | O(log n) | O(n) |

### Usage Patterns
- **Small datasets** (< 100): Linear search, Insertion sort
- **Medium datasets** (100-1000): Binary search, Quick sort
- **Large datasets** (> 1000): Binary search, Merge sort

---

## 🔗 Related Resources

- **[Algorithm Documentation](algorithms/)** - Detailed algorithm documentation
- **[Test Documentation](testing/)** - Test coverage and strategies
- **[Complexity Table](COMPLEXITY_TABLE.md)** - Performance comparison
- **[Learning Path](LEARNING_PATH.md)** - Structured learning curriculum

---

*This index is automatically generated. Do not edit manually.*  
*Run \`./scripts/generate-index.sh\` to update.*
EOF
}

# Function to backup existing index
backup_existing_index() {
    if [[ -f "$INDEX_FILE" ]]; then
        local backup_file="${INDEX_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
        cp "$INDEX_FILE" "$backup_file"
        log_info "Backed up existing index to: $(basename "$backup_file")"
    fi
}

# Function to validate generated index
validate_index() {
    local index_file="$1"
    
    # Check if file exists and is not empty
    if [[ ! -f "$index_file" ]] || [[ ! -s "$index_file" ]]; then
        log_error "Generated index file is empty or missing"
        return 1
    fi
    
    # Check if it contains expected content
    if ! grep -q "DSA Java - Algorithm Index" "$index_file"; then
        log_error "Generated index file doesn't contain expected content"
        return 1
    fi
    
    log_success "Generated index validation passed"
    return 0
}

# Main execution
main() {
    log_info "Starting automatic index generation..."
    
    # Check if we're in the right directory
    if [[ ! -f "$PROJECT_ROOT/build.gradle" ]]; then
        log_error "Not in a valid DSA Java project directory"
        exit 1
    fi
    
    # Create docs directory if it doesn't exist
    mkdir -p "$DOCS_DIR"
    
    # Find all algorithm files
    local algorithm_files=()
    while IFS= read -r file; do
        algorithm_files+=("$file")
    done < <(find_algorithm_files "$SOURCE_DIR")
    
    if [[ ${#algorithm_files[@]} -eq 0 ]]; then
        log_warning "No algorithm files found in $SOURCE_DIR"
        exit 0
    fi
    
    log_info "Found ${#algorithm_files[@]} algorithm files"
    
    # Backup existing index
    backup_existing_index
    
    # Generate new index content
    log_info "Generating new index content..."
    local temp_file=$(mktemp)
    generate_index_content "${algorithm_files[@]}" > "$temp_file"
    
    # Validate generated content
    if ! validate_index "$temp_file"; then
        rm -f "$temp_file"
        exit 1
    fi
    
    # Move temp file to final location
    mv "$temp_file" "$INDEX_FILE"
    
    log_success "Index generated successfully: $INDEX_FILE"
    log_info "Total algorithms: ${#algorithm_files[@]}"
    
    # Show summary
    echo ""
    echo "📊 Generation Summary:"
    echo "- Algorithm files scanned: ${#algorithm_files[@]}"
    echo "- Index file: $INDEX_FILE"
    echo "- Timestamp: $(date '+%Y-%m-%d %H:%M:%S')"
    
    # Check if git status shows changes
    if command -v git >/dev/null 2>&1 && [[ -d "$PROJECT_ROOT/.git" ]]; then
        cd "$PROJECT_ROOT"
        if git diff --quiet "$INDEX_FILE" 2>/dev/null; then
            log_info "No changes detected in index file"
        else
            log_warning "Index file has changed"
            echo "💡 Run 'git add docs/INDEX.md && git commit -m \"Update algorithm index\"' to commit changes"
        fi
    fi
}

# Handle command line arguments
case "${1:-}" in
    --help|-h)
        echo "Usage: $0 [OPTIONS]"
        echo ""
        echo "Options:"
        echo "  --help, -h     Show this help message"
        echo "  --check, -c    Check if index is up to date (exit with 1 if not)"
        echo "  --dry-run, -n  Show what would be generated without writing file"
        echo ""
        echo "Examples:"
        echo "  $0              # Generate index"
        echo "  $0 --check      # Check if index is current"
        echo "  $0 --dry-run    # Preview generation"
        exit 0
        ;;
    --check|-c)
        log_info "Checking if index is up to date..."
        
        # Generate temporary index
        local algorithm_files=()
        while IFS= read -r file; do
            algorithm_files+=("$file")
        done < <(find_algorithm_files "$SOURCE_DIR")
        
        local temp_file=$(mktemp)
        generate_index_content "${algorithm_files[@]}" > "$temp_file"
        
        # Compare with existing index
        if [[ -f "$INDEX_FILE" ]] && diff -q "$INDEX_FILE" "$temp_file" >/dev/null 2>&1; then
            log_success "Index is up to date"
            rm -f "$temp_file"
            exit 0
        else
            log_warning "Index is out of date"
            rm -f "$temp_file"
            exit 1
        fi
        ;;
    --dry-run|-n)
        log_info "Dry run: Showing what would be generated..."
        
        local algorithm_files=()
        while IFS= read -r file; do
            algorithm_files+=("$file")
        done < <(find_algorithm_files "$SOURCE_DIR")
        
        generate_index_content "${algorithm_files[@]}"
        exit 0
        ;;
    "")
        # Default behavior - generate index
        main
        ;;
    *)
        log_error "Unknown option: $1"
        echo "Use --help for usage information"
        exit 1
        ;;
esac
