#!/bin/bash

# Self-Healing Documentation Setup Script
# Automatically creates missing documentation structure
# Usage: ./scripts/setup-docs.sh

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

log_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Function to create directory if it doesn't exist
create_directory() {
    local dir_path="$1"
    local description="$2"
    
    if [ ! -d "$dir_path" ]; then
        log_info "Creating directory: $dir_path ($description)"
        mkdir -p "$dir_path"
        log_success "Created: $dir_path"
    else
        log_success "Directory exists: $dir_path"
    fi
}

# Function to create file if it doesn't exist
create_file() {
    local file_path="$1"
    local content="$2"
    local description="$3"
    
    if [ ! -f "$file_path" ]; then
        log_info "Creating file: $file_path ($description)"
        echo -e "$content" > "$file_path"
        log_success "Created: $file_path"
    else
        log_success "File exists: $file_path"
    fi
}

# Function to create directory with README
create_directory_with_readme() {
    local dir_path="$1"
    local description="$2"
    local readme_content="$3"
    
    create_directory "$dir_path" "$description"
    create_file "$dir_path/README.md" "$readme_content" "Directory README"
}

echo "🚀 Self-Healing Documentation Setup"
echo "=================================="
echo ""

# Create main docs directory
create_directory "docs" "Main documentation directory"

# Create required directories
echo ""
echo "📁 Creating required directories..."

create_directory "docs/algorithms" "Algorithm documentation"
create_directory "docs/testing" "Test documentation"
create_directory "docs/examples" "Usage examples"
create_directory "docs/architecture" "Project architecture"
create_directory "docs/templates" "Documentation templates"
create_directory "docs/assets" "Images and diagrams"

# Create main documentation files
echo ""
echo "📄 Creating required documentation files..."

# docs/README.md
create_file "docs/README.md" "# DSA Java Documentation

> 🎯 **Comprehensive documentation for Data Structures and Algorithms in Java**

---

## 📚 Documentation Structure

### 📁 Directories

| Directory | Purpose | Contents |
|------------|---------|----------|
| **algorithms/** | Algorithm documentation | Individual algorithm docs |
| **testing/** | Test documentation | Test strategies and results |
| **examples/** | Usage examples | Practical implementation examples |
| **architecture/** | Project architecture | Design decisions and patterns |
| **templates/** | Documentation templates | Reusable template files |
| **assets/** | Visual assets | Images, diagrams, charts |

---

## 🚀 Quick Start

### For Developers
- **[Algorithm Index](INDEX.md)** - Find algorithm documentation
- **[Complexity Table](COMPLEXITY_TABLE.md)** - Performance comparison
- **[Test Case Matrix](TEST_CASE_MATRIX.md)** - Test coverage

### For Learners
- **[Learning Path](LEARNING_PATH.md)** - Structured curriculum
- **[FAQ](FAQ.md)** - Common questions
- **[Glossary](GLOSSARY.md)** - Technical terms

### For Contributors
- **[Style Guide](STYLE_GUIDE.md)** - Documentation standards
- **[Naming Conventions](NAMING_CONVENTIONS.md)** - Naming rules
- **[Error Handling Guide](ERROR_HANDLING_GUIDE.md)** - Best practices

---

## 📊 Project Statistics

- **Total Algorithms**: TBD
- **Test Coverage**: TBD
- **Documentation Coverage**: TBD

---

## 🔧 Development

### Adding New Documentation
1. Use templates from \`templates/\` directory
2. Follow [Style Guide](STYLE_GUIDE.md)
3. Update [INDEX.md](INDEX.md)
4. Run documentation checks

### Documentation Standards
- ✅ Follow markdown best practices
- ✅ Include code examples
- ✅ Add complexity analysis
- ✅ Provide usage examples

---

## 📞 Support

For documentation issues:
- 📋 Create an issue with \`documentation\` label
- 📧 Contact maintainers
- 📖 Check [FAQ](FAQ.md)

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Generated by**: Self-Healing Documentation Setup*" "Main documentation index"

# docs/INDEX.md
create_file "docs/INDEX.md" "# DSA Java - Master Documentation Index

> 🎯 **Central navigation hub for all DSA Java documentation**

---

## 📊 Code-to-Doc Mapping Table

| Java File | Algorithm Doc | Test File | Test Doc | Category | Status |
|-----------|---------------|-----------|----------|----------|--------|
| **[AlgorithmName.java](../AlgorithmName.java)** | [📄](algorithms/AlgorithmName_Documentation.md) | [🧪](../AlgorithmName_Test.java) | [📋](testing/AlgorithmName_Test_Documentation.md) | Category | ✅ |

---

## 📚 Algorithm Categories

### 🔍 Search Algorithms
*Coming soon...*

### 📊 Sorting Algorithms
*Coming soon...*

### 🔗 Data Structures
*Coming soon...*

---

## 🔧 Development Commands

- **Generate Index**: \`./gradlew generateDocsIndex\`
- **Validate Docs**: \`./gradlew validateDocs\`
- **Build All**: \`./gradlew build\`

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Auto-generated by**: Documentation Generator*" "Master documentation index"

# docs/COMPLEXITY_TABLE.md
create_file "docs/COMPLEXITY_TABLE.md" "# Algorithm Complexity Analysis

> 📊 **Comprehensive complexity analysis for all DSA algorithms**

---

## 📈 Time Complexity Comparison

| Algorithm | Best | Average | Worst | Space | Stable | In-Place |
|-----------|-------|----------|--------|-------|--------|----------|
| **Binary Search** | O(1) | O(log n) | O(log n) | O(1) | N/A | ✅ |
| **Linear Search** | O(1) | O(n) | O(n) | O(1) | N/A | ✅ |
| **Quick Sort** | O(n log n) | O(n log n) | O(n²) | O(log n) | ❌ | ✅ |
| **Merge Sort** | O(n log n) | O(n log n) | O(n log n) | O(n) | ✅ | ❌ |

---

## 🔍 Search Algorithms

| Algorithm | Data Structure | Time | Space | Use Case |
|-----------|----------------|------|-------|----------|
| **Binary Search** | Sorted Array | O(log n) | O(1) | Fast search in sorted data |
| **Linear Search** | Array/List | O(n) | O(1) | Simple search, unsorted data |

---

## 📊 Sorting Algorithms

| Algorithm | Data Structure | Time | Space | Stable | When to Use |
|-----------|----------------|------|-------|--------|------------|
| **Quick Sort** | Array | O(n log n) avg | O(log n) | No | General purpose, fastest average |
| **Merge Sort** | Array | O(n log n) | O(n) | Yes | Stable sort needed |
| **Bubble Sort** | Array | O(n²) | O(1) | Yes | Educational purposes only |
| **Insertion Sort** | Array | O(n²) | O(1) | Yes | Nearly sorted data |

---

## 🔗 Data Structures

| Structure | Operations | Time | Space | Use Case |
|-----------|------------|------|-------|----------|
| **Array** | Random Access | O(1) | O(n) | Fixed-size collections |
| **Linked List** | Insert/Delete | O(1) | O(n) | Dynamic collections |
| **Stack** | Push/Pop | O(1) | O(n) | LIFO operations |
| **Queue** | Enqueue/Dequeue | O(1) | O(n) | FIFO operations |

---

## 📋 Complexity Classes

| Class | Description | Examples |
|-------|-------------|----------|
| **O(1)** | Constant time | Array access, stack push/pop |
| **O(log n)** | Logarithmic | Binary search, tree operations |
| **O(n)** | Linear | Linear search, array traversal |
| **O(n log n)** | Linearithmic | Efficient sorting algorithms |
| **O(n²)** | Quadratic | Bubble sort, insertion sort |
| **O(n³)** | Cubic | Matrix multiplication |

---

## 🎯 Selection Guide

### For Small Datasets (< 100 elements)
- **Search**: Linear Search
- **Sort**: Insertion Sort
- **Structure**: Array

### For Medium Datasets (100-1000 elements)
- **Search**: Binary Search (if sorted)
- **Sort**: Quick Sort
- **Structure**: Linked List

### For Large Datasets (> 1000 elements)
- **Search**: Binary Search
- **Sort**: Quick Sort or Merge Sort
- **Structure**: Choose based on operations

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Auto-generated by**: Documentation Generator*" "Algorithm complexity reference"

# docs/TEST_CASE_MATRIX.md
create_file "docs/TEST_CASE_MATRIX.md" "# Test Coverage Matrix

> 🧪 **Comprehensive test coverage analysis for all algorithms**

---

## 📊 Test Coverage Overview

### Test Categories
- **Basic Functionality**: Core algorithm correctness
- **Edge Cases**: Boundary conditions and special cases
- **Performance**: Efficiency and scalability testing
- **Large Datasets**: Behavior with substantial data volumes
- **Memory Efficiency**: Memory usage analysis
- **Advanced Operations**: Complex scenario testing
- **Different Data Types**: Type compatibility verification
- **Integration**: Interoperability with other components
- **Error Handling**: Invalid input and exception scenarios
- **Boundary Conditions**: Limit testing
- **Algorithm Comparison**: Comparative analysis
- **Performance Comparison**: Benchmarking against alternatives

---

## 📋 Test Coverage Matrix

### 🔍 Search Algorithms

| Algorithm | Basic Functionality | Edge Cases | Performance | Large Datasets | Memory Efficiency | Advanced Operations | Different Data Types | Integration | Error Handling | Boundary Conditions | Algorithm Comparison | Performance Comparison |
|-----------|--------------------|------------|-------------|----------------|-------------------|--------------------|---------------------|------------|---------------|-------------------|---------------------|-----------------------|
| **Binary Search** | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| **Linear Search** | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |

### 📊 Sorting Algorithms

| Algorithm | Basic Functionality | Edge Cases | Performance | Large Datasets | Memory Efficiency | Advanced Operations | Different Data Types | Integration | Error Handling | Boundary Conditions | Algorithm Comparison | Performance Comparison |
|-----------|--------------------|------------|-------------|----------------|-------------------|--------------------|---------------------|------------|---------------|-------------------|---------------------|-----------------------|
| **Quick Sort** | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| **Merge Sort** | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| **Bubble Sort** | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| **Insertion Sort** | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| **Selection Sort** | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |

---

## 📈 Coverage Statistics

### Overall Coverage
- **Total Algorithms**: TBD
- **Test Methods per Algorithm**: 12
- **Total Test Methods**: TBD
- **Coverage Percentage**: TBD%

### Category Distribution
| Category | Algorithms Covered | Coverage Rate | Priority |
|----------|-------------------|---------------|----------|
| **Basic Functionality** | TBD | TBD% | Critical |
| **Edge Cases** | TBD | TBD% | Critical |
| **Performance** | TBD | TBD% | High |
| **Error Handling** | TBD | TBD% | High |
| **Large Datasets** | TBD | TBD% | Medium |
| **Memory Efficiency** | TBD | TBD% | Medium |

---

## 🧪 Test Methodology

### Test Categories Explained

#### ✅ Basic Functionality Tests
**Purpose**: Validate standard functionality with valid inputs
**Test Cases**: Typical inputs, standard operations, expected outputs

#### ✅ Edge Cases Tests
**Purpose**: Test boundary conditions and extreme values
**Test Cases**: Empty data, single elements, maximum values, duplicates

#### ✅ Performance Tests
**Purpose**: Measure algorithm efficiency and scalability
**Test Cases**: Different input sizes, execution time, memory usage

#### ✅ Error Handling Tests
**Purpose**: Test error handling and input validation
**Test Cases**: Invalid inputs, null values, type mismatches

---

## 📊 Performance Benchmarks

### Execution Time Comparison
| Algorithm | 100 elements | 1,000 elements | 10,000 elements | 100,000 elements |
|-----------|--------------|----------------|------------------|-------------------|
| **Binary Search** | ~0.001ms | ~0.002ms | ~0.003ms | ~0.004ms |
| **Linear Search** | ~0.001ms | ~0.01ms | ~0.1ms | ~1ms |
| **Quick Sort** | ~0.01ms | ~0.1ms | ~1ms | ~10ms |
| **Merge Sort** | ~0.01ms | ~0.1ms | ~1ms | ~10ms |

### Memory Usage Comparison
| Algorithm | 100 elements | 1,000 elements | 10,000 elements |
|-----------|--------------|----------------|------------------|
| **In-place algorithms** | ~1KB | ~10KB | ~100KB |
| **Out-of-place** | ~2KB | ~20KB | ~200KB |

---

## 🎯 Test Quality Metrics

### Coverage Targets
- **Code Coverage**: 85%+
- **Branch Coverage**: 80%+
- **Edge Case Coverage**: 95%+
- **Performance Coverage**: 100%

### Quality Gates
- ✅ All basic functionality tests pass
- ✅ All edge cases are covered
- ✅ Performance benchmarks meet expectations
- ✅ Error handling is comprehensive

---

## 🔧 Test Execution

### Running Tests
```bash
# Run all tests
./gradlew test

# Run specific algorithm tests
./gradlew test --tests BinarySearch_Test

# Run performance tests
./gradlew runPerformanceTests

# Generate coverage report
./gradlew jacocoTestReport
```

### Test Reports
- **HTML Report**: \`build/reports/jacoco/test/html/index.html\`
- **XML Report**: \`build/reports/jacoco/test/jacocoTestReport.xml\`
- **Coverage Summary**: Console output

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Auto-generated by**: Documentation Generator*" "Test coverage analysis"

# docs/GLOSSARY.md
create_file "docs/GLOSSARY.md" "# DSA Java Glossary

> 📚 **Technical terminology and concepts used in this project**

---

## 🔤 Algorithm Terms

### A
**Algorithm**: A step-by-step procedure for solving a problem or accomplishing a task.

**Array**: A fixed-size collection of elements of the same type stored in contiguous memory locations.

**Asymptotic Analysis**: Method of describing the limiting behavior of an algorithm when the input size tends towards infinity.

### B
**Big-O Notation**: Mathematical notation describing the limiting behavior of a function when the argument tends towards a particular value or infinity.

**Binary Search**: Search algorithm that finds the position of a target value within a sorted array.

**Bubble Sort**: Simple sorting algorithm that repeatedly steps through the list, compares adjacent elements and swaps them if they are in the wrong order.

### C
**Complexity**: Measure of the resources required by an algorithm, typically time and space.

**Constant Time (O(1))**: Algorithm execution time that does not depend on input size.

### D
**Data Structure**: Particular way of organizing and storing data in a computer so that it can be accessed and modified efficiently.

**Divide and Conquer**: Algorithm design paradigm that recursively breaks down a problem into two or more sub-problems.

### E
**Edge Case**: Test case at the extreme operating conditions of an algorithm.

### F
**First-In-First-Out (FIFO)**: Data ordering principle where the first element added to the collection will be the first one to be removed.

### G
**Graph**: Abstract data type consisting of a set of vertices and a set of edges connecting pairs of vertices.

### H
**Heap**: Specialized tree-based data structure that satisfies the heap property.

### I
**In-Place Algorithm**: Algorithm that transforms input using no auxiliary data structure.

**Insertion Sort**: Simple sorting algorithm that builds the final sorted array one item at a time.

### L
**Last-In-First-Out (LIFO)**: Data ordering principle where the last element added to the collection will be the first one to be removed.

**Linear Search**: Search algorithm that sequentially checks each element in a list until a match is found.

**Linked List**: Data structure consisting of nodes where each node contains data and a pointer to the next node.

### M
**Merge Sort**: Divide-and-conquer algorithm that divides the array into two halves, recursively sorts them, and then merges them.

**Memory Complexity**: Amount of memory an algorithm needs to run to completion.

### O
**Optimization**: Process of modifying a system to make some features of it work more efficiently or use fewer resources.

### P
**Performance**: Measure of how efficiently a computer system uses available resources.

**Priority Queue**: Abstract data type similar to a regular queue but where each element has a priority associated with it.

### Q
**Queue**: Collection of entities that are maintained in a sequence and can be modified by the addition of entities at one end and removal from the other.

**Quick Sort**: Divide-and-conquer sorting algorithm that picks an element as a pivot and partitions the array around it.

### R
**Recursion**: Method where the solution to a problem depends on solutions to smaller instances of the same problem.

### S
**Search Algorithm**: Algorithm for retrieving information stored within some data structure, or calculated in the search space of a problem domain.

**Selection Sort**: In-place comparison sorting algorithm with O(n²) time complexity.

**Space Complexity**: Amount of memory space required by an algorithm to run to completion.

**Stack**: Abstract data type that serves as a collection of elements, with two main principal operations: push and pop.

**Stable Sort**: Sorting algorithm that maintains the relative order of equal elements.

### T
**Time Complexity**: Computational complexity that describes the amount of time it takes to run an algorithm.

**Tree**: Abstract data type that simulates a hierarchical tree structure, with a root value and subtrees of children with a parent-child relationship.

---

## 📊 Data Structures

### Linear Data Structures
| Structure | Operations | Time Complexity | Use Cases |
|----------|------------|------------------|-----------|
| **Array** | Random Access | O(1) | Fixed-size collections |
| **Linked List** | Insert/Delete | O(1) | Dynamic collections |
| **Stack** | Push/Pop | O(1) | LIFO operations |
| **Queue** | Enqueue/Dequeue | O(1) | FIFO operations |

### Non-Linear Data Structures
| Structure | Operations | Time Complexity | Use Cases |
|----------|------------|------------------|-----------|
| **Tree** | Search/Insert | O(log n) | Hierarchical data |
| **Graph** | Traversal | O(V+E) | Network relationships |
| **Heap** | Insert/Extract | O(log n) | Priority operations |

---

## 🔢 Algorithm Classifications

### By Time Complexity
| Class | Description | Examples |
|-------|-------------|----------|
| **O(1)** | Constant time | Array access |
| **O(log n)** | Logarithmic | Binary search |
| **O(n)** | Linear | Linear search |
| **O(n log n)** | Linearithmic | Efficient sorting |
| **O(n²)** | Quadratic | Simple sorting |
| **O(2ⁿ)** | Exponential | Recursive algorithms |

### By Space Complexity
| Class | Description | Examples |
|-------|-------------|----------|
| **O(1)** | Constant space | In-place algorithms |
| **O(log n)** | Logarithmic space | Tree algorithms |
| **O(n)** | Linear space | Array copying |
| **O(n log n)** | Linearithmic space | Merge sort |

---

## 🎯 Common Patterns

### Search Patterns
- **Linear Search**: Check each element sequentially
- **Binary Search**: Divide search space in half
- **Hash Table**: Direct key-value lookup

### Sorting Patterns
- **Comparison Sort**: Compare elements to order them
- **Counting Sort**: Count occurrences of elements
- **Radix Sort**: Sort digits of numbers

### Data Structure Patterns
- **Array**: Contiguous memory allocation
- **Linked List**: Pointer-based allocation
- **Tree**: Hierarchical organization

---

## 📚 Related Resources

- **[Algorithm Complexity](COMPLEXITY_TABLE.md)** - Detailed complexity analysis
- **[Learning Path](LEARNING_PATH.md)** - Structured learning
- **[FAQ](FAQ.md)** - Common questions

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Auto-generated by**: Documentation Generator*" "Technical terminology glossary"

# docs/FAQ.md
create_file "docs/FAQ.md" "# Frequently Asked Questions

> ❓ **Common questions about DSA Java algorithms and this project**

---

## 🚀 Getting Started

### Q: What Java version do I need?
**A**: Java 17 or higher is required. The project uses modern Java features and is optimized for Java 17 LTS.

### Q: How do I run the algorithms?
**A**: 
```bash
# Run specific algorithm
java -cp build/libs/dsa-java-algorithms-1.0.0-fat.jar BinarySearch

# Run all algorithms
./gradlew runAllAlgorithms

# Interactive mode
./gradlew run --args="interactive"
```

### Q: How do I run tests?
**A**:
```bash
# Run all tests
./gradlew test

# Run specific test
./gradlew test --tests BinarySearch_Test

# Generate coverage report
./gradlew jacocoTestReport
```

---

## 📚 Algorithm Questions

### Q: Which sorting algorithm is fastest?
**A**: It depends on the use case:
- **Quick Sort**: Fastest average case, O(n log n)
- **Merge Sort**: Guaranteed O(n log n), stable
- **Insertion Sort**: Best for nearly sorted data, O(n) best case

### Q: When should I use binary search?
**A**: Use binary search when:
- Data is sorted
- Multiple searches will be performed
- Large dataset (> 100 elements)
- Search time is critical

### Q: What's the difference between array and linked list?
**A**: 
| Feature | Array | Linked List |
|---------|-------|-------------|
| **Access** | O(1) random | O(n) sequential |
| **Insert/Delete** | O(n) | O(1) at beginning |
| **Memory** | Contiguous | Distributed |
| **Size** | Fixed | Dynamic |

---

## 🧪 Testing Questions

### Q: How comprehensive are the tests?
**A**: Each algorithm has 12 standardized test categories:
- Basic functionality
- Edge cases
- Performance benchmarks
- Large datasets
- Memory efficiency
- Error handling
- And more...

### Q: What does test coverage mean?
**A**: Test coverage measures how much of your code is executed by tests. This project targets 85%+ coverage.

### Q: How do I interpret test results?
**A**: 
- ✅ **Passed**: Test executed successfully
- ❌ **Failed**: Test failed - check the error message
- ⚠️ **Skipped**: Test was intentionally skipped

---

## 📊 Performance Questions

### Q: How are algorithms benchmarked?
**A**: Algorithms are benchmarked on:
- Different input sizes (100, 1K, 10K, 100K elements)
- Execution time measurement
- Memory usage analysis
- Comparison with theoretical complexity

### Q: Why do some algorithms perform differently than expected?
**A**: Real-world performance depends on:
- Hardware specifications
- JVM optimizations
- Input data patterns
- Implementation details

---

## 🔧 Development Questions

### Q: How do I add a new algorithm?
**A**: Follow the contribution workflow:
1. Create algorithm class following naming conventions
2. Implement 12 test methods
3. Create documentation using templates
4. Update INDEX.md
5. Run tests and ensure 100% coverage

### Q: What are the coding standards?
**A**: 
- Follow Java naming conventions
- Use 63 standard imports
- Include interactive menu
- Add comprehensive error handling
- Document with JavaDoc

### Q: How do I debug algorithm issues?
**A**: 
- Check [Troubleshooting Guide](TROUBLESHOOTING.md)
- Use debug output in algorithms
- Run tests with detailed logging
- Check edge cases and boundary conditions

---

## 📖 Documentation Questions

### Q: How is the documentation organized?
**A**: Documentation is organized into:
- **algorithms/**: Individual algorithm docs
- **testing/**: Test documentation
- **examples/**: Usage examples
- **templates/**: Reusable templates
- **architecture/**: Project structure

### Q: How do I contribute to documentation?
**A**: 
- Follow the [Style Guide](STYLE_GUIDE.md)
- Use templates from **templates/** directory
- Update relevant index files
- Ensure all links work correctly

---

## 🏗️ Architecture Questions

### Q: Why are there so many imports?
**A**: Each algorithm includes 63 standard imports to demonstrate Java's ecosystem and ensure compatibility with various use cases.

### Q: How is the project structured?
**A**: 
```
dsa-java/
├── src/main/java/          # Algorithm implementations
├── src/test/java/           # Test cases
├── docs/                    # Documentation
├── scripts/                 # Utility scripts
└── build.gradle            # Build configuration
```

### Q: Can I use this in my own project?
**A**: Yes! The code is open-source under MIT license. You can:
- Use algorithms in your projects
- Learn from implementations
- Contribute improvements
- Fork and modify

---

## 🚨 Troubleshooting

### Q: Build fails with compilation errors
**A**: 
- Check Java version (requires Java 17+)
- Verify all imports are included
- Check for syntax errors
- Run `./gradlew clean build`

### Q: Tests fail with assertion errors
**A**: 
- Check test data and expected values
- Verify algorithm implementation
- Review edge case handling
- Check for off-by-one errors

### Q: Documentation generation fails
**A**: 
- Verify all algorithm files exist
- Check file permissions
- Ensure directory structure is correct
- Run `./gradlew generateDocsIndex`

---

## 📞 Support

### Q: How do I report issues?
**A**: 
1. Check existing issues
2. Create new issue with:
   - Clear description
   - Steps to reproduce
   - Expected vs actual behavior
   - Environment details
3. Add appropriate labels

### Q: How do I ask questions?
**A**: 
- Check [FAQ](FAQ.md) first
- Search existing issues
- Create issue with `question` label
- Provide context and details

### Q: Where can I get help?
**A**: 
- **Documentation**: Check docs/ directory
- **Issues**: GitHub Issues
- **Discussions**: GitHub Discussions
- **Community**: Project maintainers

---

## 🎯 Best Practices

### Q: What are the best practices for learning?
**A**: 
- Follow the [Learning Path](LEARNING_PATH.md)
- Start with basic algorithms
- Implement before using libraries
- Practice with test cases
- Understand complexity analysis

### Q: How do I prepare for interviews?
**A**: 
- Follow the interview track in [Learning Tracks](LEARNING_TRACKS.md)
- Practice common algorithm problems
- Understand time/space complexity
- Practice whiteboard coding

### Q: What are common mistakes to avoid?
**A**: 
- Not testing edge cases
- Ignoring error handling
- Off-by-one errors
- Memory leaks
- Inefficient loops

---

## 📈 Advanced Topics

### Q: How do I optimize algorithm performance?
**A**: 
- Profile with performance tests
- Analyze bottlenecks
- Consider data structure choice
- Optimize inner loops
- Use appropriate algorithms

### Q: When should I use recursion vs iteration?
**A**: 
- **Recursion**: Tree structures, divide-and-conquer
- **Iteration**: Linear processing, performance-critical
- Consider stack overflow with deep recursion
- Tail recursion optimization

---

## 🔗 Related Resources

- **[Complexity Table](COMPLEXITY_TABLE.md)** - Performance comparison
- **[Test Case Matrix](TEST_CASE_MATRIX.md)** - Test coverage
- **[Troubleshooting Guide](TROUBLESHOOTING.md)** - Common issues
- **[Style Guide](STYLE_GUIDE.md)** - Documentation standards

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Auto-generated by**: Documentation Generator*" "Frequently asked questions"

# docs/LEARNING_PATH.md
create_file "docs/LEARNING_PATH.md" "# Structured Learning Path

> 🎓 **Comprehensive curriculum for learning Data Structures and Algorithms in Java**

---

## 📚 Learning Overview

This learning path is designed to take you from beginner to advanced level in Data Structures and Algorithms (DSA) with Java. The curriculum is structured into phases, each building upon the previous one.

### 🎯 Learning Objectives
- Master fundamental data structures
- Understand algorithm design principles
- Analyze time and space complexity
- Implement efficient solutions
- Prepare for technical interviews

---

## 📅 Learning Schedule

### 🌱 Phase 1: Foundations (Weeks 1-2)

#### Week 1: Java Basics & Arrays
**Goal**: Master Java fundamentals and array operations

**Topics**:
- Java syntax and data types
- Array manipulation
- Basic algorithmic thinking
- Time complexity introduction

**Algorithms**:
- [Insert Element](../InsertElement.java) - Array insertion
- [Remove Element](../RemoveElement.java) - Array deletion
- [Traversal](../Traversal.java) - Array traversal

**Learning Objectives**:
- ✅ Understand array indexing and manipulation
- ✅ Implement basic array operations
- ✅ Analyze O(n) operations
- ✅ Handle edge cases (empty array, single element)

**Practice Exercises**:
```java
// Exercise 1: Find maximum element
public int findMax(int[] arr) {
    // Implementation
}

// Exercise 2: Reverse array in-place
public void reverseArray(int[] arr) {
    // Implementation
}

// Exercise 3: Check if array is sorted
public boolean isSorted(int[] arr) {
    // Implementation
}
```

#### Week 2: Linear Search & Analysis
**Goal**: Master simple search algorithms and complexity analysis

**Topics**:
- Linear search implementation
- Algorithm analysis basics
- Big-O notation
- Performance measurement

**Algorithms**:
- [Linear Search](../LinearSearch.java) - Basic linear search
- [Linear Search with Frequency](../LinearSearchWithFrequency.java) - Enhanced search

**Learning Objectives**:
- ✅ Implement linear search from scratch
- ✅ Understand time complexity analysis
- ✅ Measure algorithm performance
- ✅ Handle multiple occurrences

---

### 🔍 Phase 2: Search Algorithms (Weeks 3-4)

#### Week 3: Binary Search
**Goal**: Master efficient searching in sorted data

**Topics**:
- Binary search algorithm
- Divide and conquer principle
- Recursive vs iterative implementation
- Search algorithm comparison

**Algorithms**:
- [Binary Search](../BinarySearch.java) - Efficient search in sorted arrays

**Learning Objectives**:
- ✅ Implement binary search
- ✅ Understand divide and conquer
- ✅ Compare search algorithms
- ✅ Handle edge cases in binary search

**Practice Exercises**:
```java
// Exercise 1: Find first occurrence
public int findFirst(int[] arr, int target) {
    // Implementation
}

// Exercise 2: Search in rotated array
public int searchRotated(int[] nums, int target) {
    // Implementation
}

// Exercise 3: Find range of target
public int[] searchRange(int[] nums, int target) {
    // Implementation
}
```

#### Week 4: Search Applications
**Goal**: Apply search algorithms to practical problems

**Topics**:
- Search in complex data structures
- Multiple search techniques
- Search optimization strategies

**Learning Objectives**:
- ✅ Apply search to real problems
- ✅ Optimize search performance
- ✅ Choose appropriate search algorithm

---

### 📊 Phase 3: Sorting Algorithms (Weeks 5-8)

#### Week 5: Basic Sorting
**Goal**: Understand fundamental sorting algorithms

**Topics**:
- Bubble sort mechanics
- Selection sort principles
- Sorting stability concepts
- Sorting performance analysis

**Algorithms**:
- [Bubble Sort](../BubbleSort.java) - Simple sorting
- [Selection Sort](../SelectionSort.java) - Selection-based sorting

**Learning Objectives**:
- ✅ Implement basic sorting algorithms
- ✅ Understand sorting stability
- ✅ Analyze sorting performance
- ✅ Compare sorting approaches

#### Week 6: Insertion Sort
**Goal**: Master adaptive sorting

**Topics**:
- Insertion sort algorithm
- Adaptive sorting behavior
- Nearly sorted data optimization
- Insertion sort applications

**Algorithms**:
- [Insertion Sort](../InsertionSort.java) - Incremental sorting

**Learning Objectives**:
- ✅ Implement insertion sort
- ✅ Understand adaptive behavior
- ✅ Optimize for nearly sorted data
- ✅ Identify best use cases

#### Week 7: Merge Sort
**Goal**: Master divide-and-conquer sorting

**Topics**:
- Merge sort algorithm
- Recursive sorting
- Merge operation
- Stable sorting

**Algorithms**:
- [Merge Sort Algorithm](../MergeSortAlgorithm.java) - Divide-and-conquer sorting

**Learning Objectives**:
- ✅ Implement merge sort
- ✅ Understand recursion in sorting
- ✅ Implement merge operation
- ✅ Analyze space complexity

#### Week 8: Quick Sort
**Goal**: Master efficient practical sorting

**Topics**:
- Quick sort algorithm
- Partitioning strategies
- Pivot selection
- Worst-case scenarios

**Algorithms**:
- [Quick Sort Algorithm](../QuickSortAlgorithm.java) - Partition-based sorting

**Learning Objectives**:
- ✅ Implement quick sort
- ✅ Understand partitioning
- ✅ Handle worst-case scenarios
- ✅ Optimize pivot selection

---

### 🔗 Phase 4: Data Structures (Weeks 9-12)

#### Week 9: Linked Lists
**Goal**: Master pointer-based data structures

**Topics**:
- Linked list fundamentals
- Node-based structures
- Memory management
- Linked list operations

**Algorithms**:
- [Linked List with Addresses](../LinkedListWithAddresses.java) - Pointer-based list
- [Singly Linked List](../SinglyLinkedList.java) - Single-direction list

**Learning Objectives**:
- ✅ Implement linked list operations
- ✅ Understand memory management
- ✅ Compare with array operations
- ✅ Handle pointer operations

#### Week 10: Stacks
**Goal**: Master LIFO data structures

**Topics**:
- Stack implementation
- LIFO principle
- Stack applications
- Array vs linked stack

**Algorithms**:
- [Stack Operations](../StackOperations.java) - Stack implementation

**Learning Objectives**:
- ✅ Implement stack operations
- ✅ Understand LIFO principle
- ✅ Apply stacks to real problems
- ✅ Compare stack implementations

#### Week 11: Queues
**Goal**: Master FIFO data structures

**Topics**:
- Queue implementations
- FIFO principle
- Circular queues
- Priority queues

**Algorithms**:
- [Linear Queue](../LinearQueue.java) - Basic queue
- [Circular Queue](../CircularQueue.java) - Circular buffer
- [Priority Queue Operations](../PriorityQueueOperations.java) - Priority-based queue
- [Queue Using Array](../QueueUsingArray.java) - Array-based queue

**Learning Objectives**:
- ✅ Implement different queue types
- ✅ Understand FIFO principle
- ✅ Compare queue implementations
- ✅ Apply queues to algorithms

#### Week 12: Advanced Data Structures
**Goal**: Explore complex data structures

**Topics**:
- Deques (double-ended queues)
- Priority queue applications
- Data structure selection
- Performance considerations

**Algorithms**:
- [Deque Operations](../DequeOperations.java) - Double-ended queue

**Learning Objectives**:
- ✅ Implement advanced data structures
- ✅ Choose appropriate structures
- ✅ Understand performance trade-offs
- ✅ Apply to algorithm design

---

### 🔢 Phase 5: Specialized Topics (Weeks 13-14)

#### Week 13: Array Operations & Matrix
**Goal**: Master array manipulation algorithms

**Topics**:
- Advanced array operations
- Matrix operations
- Sparse matrices
- Array optimization

**Algorithms**:
- [Matrix Multiplication](../MatrxMultiplication.java) - Matrix operations
- [Sparse Matrix](../SparseMatrix.java) - Memory-efficient matrices

**Learning Objectives**:
- ✅ Implement matrix operations
- ✅ Optimize for sparse data
- ✅ Understand 2D arrays
- ✅ Apply matrix algorithms

#### Week 14: Statistical Analysis
**Goal**: Master statistical algorithms

**Topics**:
- Order statistics
- Finding min/max elements
- Statistical measures
- Data analysis algorithms

**Algorithms**:
- [Second Smallest Second Largest](../SecondSmallestSecondLargest.java) - Order statistics
- [Smallest Largest](../SmallestLargest.java) - Basic statistics

**Learning Objectives**:
- ✅ Implement statistical algorithms
- ✅ Find order statistics
- ✅ Analyze data efficiently
- ✅ Apply to real datasets

---

## 📊 Progress Tracking

### Weekly Milestones
| Week | Milestone | Success Criteria |
|------|-----------|------------------|
| 1-2 | Foundations | Implement basic array operations |
| 3-4 | Search | Master search algorithms |
| 5-8 | Sorting | Implement all sorting algorithms |
| 9-12 | Data Structures | Master linear data structures |
| 13-14 | Advanced | Complete specialized topics |

### Assessment Criteria
- **Code Quality**: Clean, well-documented code
- **Test Coverage**: 100% for implemented algorithms
- **Performance**: Meets theoretical complexity
- **Understanding**: Can explain algorithm choices

### Self-Evaluation
After each phase, ask yourself:
- ✅ Can I implement the algorithms from scratch?
- ✅ Do I understand the time/space complexity?
- ✅ Can I choose the right algorithm for a problem?
- ✅ Can I optimize algorithm performance?

---

## 🎯 Interview Preparation

### Interview Questions by Category

#### Search Algorithms
- Implement binary search
- Find first/last occurrence
- Search in rotated array
- Search in 2D matrix

#### Sorting Algorithms
- Implement quick sort
- Merge sort vs quick sort
- Sort in O(n) time (counting sort)
- Sort linked list

#### Data Structures
- Implement stack using queues
- Implement queue using stacks
- LRU cache implementation
- Find cycle in linked list

#### Problem Solving
- Two sum problem
- Three sum problem
- Container with most water
- Trapping rain water

---

## 📚 Additional Resources

### Recommended Books
- **"Introduction to Algorithms"** by Cormen et al.
- **"Algorithms"** by Robert Sedgewick
- **"Clean Code"** by Robert Martin

### Online Resources
- **LeetCode** - Practice problems
- **HackerRank** - Coding challenges
- **GeeksforGeeks** - Algorithm tutorials
- **Visualgo** - Algorithm visualization

### Practice Platforms
- **LeetCode** - Interview preparation
- **HackerRank** - Skill assessment
- **Codeforces** - Competitive programming
- **InterviewBit** - Company-specific questions

---

## 🔧 Study Tips

### Effective Learning
1. **Implement First**: Code before reading theory
2. **Understand Complexity**: Analyze every algorithm
3. **Practice Regularly**: Daily coding practice
4. **Teach Others**: Explain concepts to solidify understanding

### Common Mistakes to Avoid
- ❌ Memorizing without understanding
- ❌ Skipping edge cases
- ❌ Ignoring space complexity
- ❌ Not practicing enough

### Success Factors
- ✅ Consistent practice schedule
- ✅ Understanding fundamentals deeply
- ✅ Implementing from scratch
- ✅ Solving diverse problems

---

## 🎓 Certification Path

### Beginner Level
- Complete Phase 1-2
- Implement 10+ algorithms
- Understand basic complexity
- Solve 50+ practice problems

### Intermediate Level
- Complete Phase 3-4
- Implement 20+ algorithms
- Understand all complexities
- Solve 200+ practice problems

### Advanced Level
- Complete Phase 5
- Implement 30+ algorithms
- Optimize algorithm performance
- Solve 500+ practice problems

---

## 📞 Support

### Getting Help
- **Documentation**: Check algorithm docs
- **Community**: GitHub Discussions
- **Issues**: Report problems
- **Study Groups**: Join learning communities

### Progress Tracking
- **Weekly Goals**: Set achievable targets
- **Code Review**: Review implementations
- **Performance**: Measure improvement
- **Feedback**: Seek constructive criticism

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Auto-generated by**: Documentation Generator*" "Structured learning curriculum"

# docs/STYLE_GUIDE.md
create_file "docs/STYLE_GUIDE.md" "# Documentation Style Guide

> 📝 **Standards and guidelines for creating consistent, professional documentation**

---

## 🎯 Documentation Principles

### Core Values
- **Clarity**: Easy to understand for all skill levels
- **Consistency**: Uniform formatting and structure
- **Completeness**: Comprehensive coverage of topics
- **Accuracy**: Correct and up-to-date information
- **Accessibility**: Readable by diverse audiences

### Writing Philosophy
- **Audience-First**: Write for the reader, not yourself
- **Action-Oriented**: Focus on what users can do
- **Example-Driven**: Show, don't just tell
- **Progressive Disclosure**: Start simple, add complexity

---

## 📄 Document Structure

### Standard Template
```markdown
# Document Title

> Brief description of what this document covers

---

## 📋 Overview
High-level introduction and purpose

## 🎯 Key Concepts
Main concepts and terminology

## 🔧 Implementation
Technical details and code examples

## 📊 Analysis
Performance characteristics and complexity

## 🧪 Testing
Test coverage and validation

## 📚 Related Resources
Links to related documentation

---
*Footer information*
```

### Required Sections
Every documentation file must include:

1. **Title**: Clear, descriptive H1 heading
2. **Overview**: Brief introduction (2-3 sentences)
3. **Key Sections**: Organized with H2-H4 headings
4. **Code Examples**: Working, tested code snippets
5. **Related Resources**: Links to relevant documentation

---

## 🎨 Formatting Standards

### Headings
```markdown
# H1 - Document Title
## H2 - Main Sections
### H3 - Subsections
#### H4 - Detailed topics
##### H5 - Specific details (rare)
```

**Rules**:
- Use sentence case for titles
- One space between heading and text
- Don't skip heading levels
- Maximum 60 characters for H1

### Text Formatting
```markdown
- **Bold**: Emphasis and important terms
- *Italic*: Foreign words, emphasis
- `Code`: Inline code, file names
- ~~Strikethrough~~: Deprecated information
```

### Lists
```markdown
- Bullet points for unordered lists
1. Numbered lists for sequences
- Nested lists for hierarchies
```

### Code Blocks
```java
// Use language-specific highlighting
public class Example {
    // Implementation
}
```

### Links
```markdown
[Link Text](target.md)
[External Link](https://example.com)
[Reference](#section-name)
```

---

## 📝 Content Guidelines

### Writing Style

#### Tone and Voice
- **Professional**: Use clear, professional language
- **Helpful**: Focus on helping the reader
- **Concise**: Get to the point quickly
- **Active**: Use active voice when possible

#### Language Rules
- **US English**: Use American English spelling
- **Technical Terms**: Define on first use
- **Acronyms**: Define on first appearance
- **Consistency**: Use same terminology throughout

#### Sentence Structure
- **Short Sentences**: Maximum 25 words
- **Simple Language**: Avoid jargon when possible
- **Clear Transitions**: Logical flow between sections
- **Parallel Structure**: Consistent phrasing

### Content Organization

#### Information Hierarchy
1. **Most Important**: Start with key information
2. **Supporting Details**: Add context and examples
3. **Advanced Topics**: Include for completeness
4. **References**: Link to additional resources

#### Section Guidelines
- **Introduction**: What and why (2-3 sentences)
- **Body**: How and when (detailed)
- **Conclusion**: Summary and next steps

---

## 💻 Code Documentation

### Code Examples

#### Quality Standards
- **Working Code**: All examples must be tested
- **Complete**: Include necessary imports
- **Context**: Explain what code does
- **Comments**: Add clarifying comments

#### Example Format
```java
// Brief description of what this does
public class Example {
    // Implementation details
    public void method() {
        // Step-by-step explanation
    }
}
```

#### Best Practices
- **Minimal Examples**: Focus on key concepts
- **Real-World**: Use practical scenarios
- **Error Handling**: Show error cases
- **Performance**: Mention complexity

### JavaDoc Standards
```java
/**
 * Brief description of the class/method.
 * 
 * @param param Description of parameter
 * @return Description of return value
 * @throws Exception Description of when thrown
 * @since Version when introduced
 */
```

---

## 📊 Tables and Charts

### Table Formatting
```markdown
| Header 1 | Header 2 | Header 3 |
|----------|----------|----------|
| Cell 1   | Cell 2   | Cell 3   |
| Cell 4   | Cell 5   | Cell 6   |
```

**Rules**:
- **Alignment**: Left-align text, right-align numbers
- **Headers**: Use title case
- **Content**: Keep cells concise
- **Spacing**: Use pipes consistently

### Data Tables
- **Algorithm Comparison**: Include complexity, stability, use cases
- **Performance Data**: Include time, space, dataset sizes
- **Test Coverage**: Include categories, percentages, status

---

## 🔗 Linking Guidelines

### Internal Links
```markdown
[Algorithm Documentation](algorithms/AlgorithmName.md)
[Section Reference](#section-name)
[File Reference](../path/to/file.md)
```

### External Links
```markdown
[Java Documentation](https://docs.oracle.com/en/java/)
[Algorithm Wikipedia](https://en.wikipedia.org/wiki/Algorithm)
```

### Link Best Practices
- **Descriptive Text**: Use meaningful link text
- **Valid Targets**: Ensure links work
- **Consistent Format**: Follow same pattern
- **Avoid Broken Links**: Check regularly

---

## 🖼️ Visual Elements

### Images and Diagrams
```markdown
![Alt Text](path/to/image.png "Optional Title")
```

**Guidelines**:
- **Alt Text**: Describe image content
- **File Names**: Use descriptive names
- **Formats**: Prefer SVG for diagrams, PNG for screenshots
- **Size**: Optimize for web display

### Charts and Graphs
- **Purpose**: Visualize data and relationships
- **Labels**: Clear axis labels and legends
- **Colors**: Use accessible color schemes
- **Resolution**: High enough for clarity

---

## 📋 Checklists and Templates

### Algorithm Documentation Checklist
- [ ] Title and overview included
- [ ] Complexity analysis provided
- [ ] Code examples working
- [ ] Test coverage mentioned
- [ ] Related resources linked
- [ ] Internal links validated

### Quality Standards
- **Accuracy**: All information is correct
- **Completeness**: All sections filled
- **Consistency**: Formatting follows guide
- **Clarity**: Easy to understand
- **Accessibility**: Readable by all users

---

## 🔧 Maintenance Guidelines

### Regular Updates
- **Content Review**: Monthly review for accuracy
- **Link Validation**: Quarterly link checking
- **Format Updates**: Annual style guide review
- **Template Updates**: As needed for new standards

### Version Control
- **File Naming**: Use consistent naming
- **Change Tracking**: Document significant changes
- **Backup**: Keep version history
- **Review**: Peer review before publishing

---

## 🚨 Common Issues

### Formatting Problems
- **Inconsistent Headings**: Follow H1-H4 hierarchy
- **Broken Links**: Check all internal/external links
- **Code Errors**: Test all code examples
- **Image Issues**: Verify image paths and alt text

### Content Issues
- **Outdated Information**: Update regularly
- **Missing Sections**: Complete all required sections
- **Unclear Explanations**: Rewrite for clarity
- **Technical Errors**: Verify accuracy

---

## 📚 Resources and References

### Style Guides
- **Google Developer Documentation Style Guide**
- **Microsoft Writing Style Guide**
- **Apple Style Guide**
- **Mozilla Writing Style Guide**

### Tools
- **Markdown Linters**: markdownlint, remark-lint
- **Link Checkers**: lychee, markdown-link-check
- **Spell Checkers**: cSpell, markdown-spellcheck
- **Image Optimizers**: imgopt, squoosh

### Learning Resources
- **Technical Writing Courses**: Coursera, edX
- **Documentation Books**: "The Elements of Style"
- **Writing Blogs**: Write the Docs, I'd Rather Be Writing
- **Communities**: Write the Docs Slack, documentation forums

---

## 🎯 Success Metrics

### Quality Indicators
- **Readability**: Flesch-Kincaid score 60+
- **Completeness**: All required sections present
- **Accuracy**: No factual errors
- **Accessibility**: WCAG 2.1 AA compliance

### User Feedback
- **Comprehension**: Users understand content
- **Actionability**: Users can apply information
- **Navigation**: Users find needed information
- **Satisfaction**: Users find documentation helpful

---

## 📞 Support and Feedback

### Getting Help
- **Style Questions**: Ask in team discussions
- **Template Issues**: Contact documentation team
- **Tool Problems**: Check tool documentation
- **Best Practices**: Review style guide examples

### Feedback Process
- **Peer Review**: All changes reviewed
- **User Testing**: Test with target audience
- **Iterative**: Improve based on feedback
- **Documentation**: Track changes and decisions

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Auto-generated by**: Documentation Generator*" "Documentation writing standards"

# docs/ERROR_HANDLING_GUIDE.md
create_file "docs/ERROR_HANDLING_GUIDE.md" "# Error Handling Guide

> 🛡️ **Comprehensive guide to implementing robust error handling in Java algorithms**

---

## 🎯 Error Handling Philosophy

### Core Principles
- **Fail Fast**: Detect errors early and explicitly
- **Graceful Degradation**: Provide fallback behavior when possible
- **Clear Messages**: Communicate errors clearly to users
- **Consistent Patterns**: Use uniform error handling approaches
- **Logging**: Log errors for debugging and monitoring

### Error Categories
1. **Input Validation Errors**: Invalid user input
2. **Boundary Condition Errors**: Edge cases and limits
3. **Resource Errors**: Memory, file, network issues
4. **Logic Errors**: Algorithm implementation bugs
5. **System Errors**: JVM or environment issues

---

## 🛠️ Error Handling Patterns

### 1. Input Validation

#### Pattern
```java
public void processData(int[] data) {
    // Validate input
    if (data == null) {
        throw new IllegalArgumentException("Input array cannot be null");
    }
    
    if (data.length == 0) {
        throw new IllegalArgumentException("Input array cannot be empty");
    }
    
    if (data.length > MAX_SIZE) {
        throw new IllegalArgumentException("Input array too large: max " + MAX_SIZE);
    }
    
    // Process data
    // ...
}
```

#### Best Practices
- **Null Checks**: Always check for null inputs
- **Boundary Validation**: Validate array sizes, ranges
- **Type Checking**: Ensure correct data types
- **Value Validation**: Check for valid values

### 2. Resource Management

#### Pattern
```java
public void processFile(String filename) {
    FileInputStream fis = null;
    try {
        fis = new FileInputStream(filename);
        // Process file
        // ...
    } catch (FileNotFoundException e) {
        throw new RuntimeException("File not found: " + filename, e);
    } catch (IOException e) {
        throw new RuntimeException("Error reading file: " + filename, e);
    } finally {
        if (fis != null) {
            try {
                fis.close();
            } catch (IOException e) {
                // Log but don't throw
                System.err.println("Warning: Failed to close file: " + e.getMessage());
            }
        }
    }
}
```

#### Best Practices
- **Try-Catch-Finally**: Ensure resource cleanup
- **Specific Exceptions**: Catch specific exception types
- **Resource Cleanup**: Always close resources
- **Nested Exceptions**: Preserve original exception

### 3. Algorithm-Specific Errors

#### Pattern
```java
public int binarySearch(int[] arr, int target) {
    // Validate input
    if (arr == null) {
        throw new IllegalArgumentException("Array cannot be null");
    }
    
    if (!isSorted(arr)) {
        throw new IllegalArgumentException("Array must be sorted for binary search");
    }
    
    // Algorithm implementation
    int left = 0, right = arr.length - 1;
    
    while (left <= right) {
        int mid = left + (right - left) / 2;
        
        if (arr[mid] == target) {
            return mid;
        } else if (arr[mid] < target) {
            left = mid + 1;
        } else {
            right = mid - 1;
        }
    }
    
    // Return sentinel value for not found
    return -1;
}

private boolean isSorted(int[] arr) {
    for (int i = 1; i < arr.length; i++) {
        if (arr[i] < arr[i - 1]) {
            return false;
        }
    }
    return true;
}
```

#### Best Practices
- **Precondition Checks**: Validate algorithm requirements
- **Postcondition Validation**: Verify results
- **Sentinel Values**: Use clear not-found indicators
- **Helper Methods**: Extract validation logic

---

## 📊 Exception Types and Usage

### Standard Java Exceptions

#### IllegalArgumentException
```java
// Use for invalid method arguments
public void setSize(int size) {
    if (size < 0) {
        throw new IllegalArgumentException("Size cannot be negative: " + size);
    }
    this.size = size;
}
```

#### IllegalStateException
```java
// Use for invalid object state
public void pop() {
    if (isEmpty()) {
        throw new IllegalStateException("Cannot pop from empty stack");
    }
    // Implementation
}
```

#### IndexOutOfBoundsException
```java
// Use for invalid array indices
public int get(int index) {
    if (index < 0 || index >= size) {
        throw new IndexOutOfBoundsException("Index out of bounds: " + index);
    }
    return data[index];
}
```

#### NoSuchElementException
```java
// Use for missing elements in collections
public int removeFirst() {
    if (isEmpty()) {
        throw new NoSuchElementException("Cannot remove from empty collection");
    }
    // Implementation
}
```

### Custom Exceptions

#### AlgorithmException
```java
public class AlgorithmException extends RuntimeException {
    public AlgorithmException(String message) {
        super(message);
    }
    
    public AlgorithmException(String message, Throwable cause) {
        super(message, cause);
    }
}
```

#### ValidationException
```java
public class ValidationException extends RuntimeException {
    public ValidationException(String message) {
        super(message);
    }
    
    public ValidationException(String message, Throwable cause) {
        super(message, cause);
    }
}
```

---

## 🧪 Error Handling Testing

### Test Categories

#### Input Validation Tests
```java
@Test(expected = IllegalArgumentException.class)
public void testNullInput() {
    algorithm.processData(null);
}

@Test(expected = IllegalArgumentException.class)
public void testEmptyArray() {
    algorithm.processData(new int[0]);
}
```

#### Boundary Condition Tests
```java
@Test
public void testMaxSize() {
    int[] largeArray = new int[MAX_SIZE + 1];
    try {
        algorithm.processData(largeArray);
        fail("Should throw exception for oversized array");
    } catch (IllegalArgumentException e) {
        assertTrue(e.getMessage().contains("too large"));
    }
}
```

#### Error Recovery Tests
```java
@Test
public void testErrorRecovery() {
    // Test graceful degradation
    int[] invalidData = {1, 2, 3, 2, 1}; // Not sorted
    try {
        int result = algorithm.binarySearch(invalidData, 2);
        fail("Should throw exception for unsorted array");
    } catch (IllegalArgumentException e) {
        // Expected behavior
        assertTrue(e.getMessage().contains("must be sorted"));
    }
}
```

---

## 🔍 Debugging Error Handling

### Common Issues

#### 1. Swallowed Exceptions
```java
// BAD: Swallows exception
try {
    riskyOperation();
} catch (Exception e) {
    // Do nothing - bad practice
}

// GOOD: Handle or rethrow
try {
    riskyOperation();
} catch (Exception e) {
    logger.error("Operation failed", e);
    throw new RuntimeException("Operation failed", e);
}
```

#### 2. Generic Exception Handling
```java
// BAD: Catches Exception
try {
    operation();
} catch (Exception e) {
    // Too generic
}

// GOOD: Catch specific exceptions
try {
    operation();
} catch (IllegalArgumentException e) {
    // Handle input errors
} catch (IOException e) {
    // Handle I/O errors
}
```

#### 3. Missing Finally Blocks
```java
// BAD: Resource leak
FileInputStream fis = new FileInputStream("file.txt");
try {
    // Use file
} catch (IOException e) {
    // Handle exception
}
// fis never closed

// GOOD: Proper resource management
FileInputStream fis = null;
try {
    fis = new FileInputStream("file.txt");
    // Use file
} catch (IOException e) {
    // Handle exception
} finally {
    if (fis != null) {
        try {
            fis.close();
        } catch (IOException e) {
            // Log but don't throw
        }
    }
}
```

### Debugging Techniques

#### 1. Logging
```java
import java.util.logging.Logger;
import java.util.logging.Level;

public class Algorithm {
    private static final Logger logger = Logger.getLogger(Algorithm.class.getName());
    
    public void process(int[] data) {
        logger.info("Processing array of size: " + data.length);
        
        try {
            // Algorithm implementation
            logger.info("Processing completed successfully");
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Processing failed", e);
            throw e;
        }
    }
}
```

#### 2. Assertions
```java
public int binarySearch(int[] arr, int target) {
    assert arr != null : "Array cannot be null";
    assert arr.length > 0 : "Array cannot be empty";
    assert isSorted(arr) : "Array must be sorted";
    
    // Implementation
    // ...
}
```

#### 3. Debug Information
```java
public void debugProcess(int[] data) {
    System.out.println("DEBUG: Processing array");
    System.out.println("DEBUG: Array length: " + data.length);
    System.out.println("DEBUG: First element: " + data[0]);
    System.out.println("DEBUG: Last element: " + data[data.length - 1]);
    
    // Algorithm implementation
    // ...
}
```

---

## 📋 Error Handling Checklist

### Implementation Checklist
- [ ] Input validation for all public methods
- [ ] Proper exception types for different errors
- [ ] Clear error messages with context
- [ ] Resource cleanup in finally blocks
- [ ] Logging for debugging
- [ ] Documentation of thrown exceptions

### Testing Checklist
- [ ] Tests for all error conditions
- [ ] Tests for boundary conditions
- [ ] Tests for invalid inputs
- [ ] Tests for resource errors
- [ ] Tests for error recovery
- [ ] Tests for exception messages

### Documentation Checklist
- [ ] Document all thrown exceptions
- [ ] Document error conditions
- [ ] Provide error handling examples
- [ ] Document error recovery strategies
- [ ] Include troubleshooting guide

---

## 🚀 Best Practices Summary

### Do's
✅ **Validate Input**: Always validate method arguments  
✅ **Use Specific Exceptions**: Choose appropriate exception types  
✅ **Provide Context**: Include relevant information in error messages  
✅ **Log Errors**: Log errors for debugging  
✅ **Clean Resources**: Always clean up resources  
✅ **Document Exceptions**: Document all thrown exceptions  
✅ **Test Errors**: Test all error conditions  

### Don'ts
❌ **Swallow Exceptions**: Don't catch and ignore exceptions  
❌ **Use Generic Exceptions**: Avoid catching Exception unless necessary  
❌ **Return Error Codes**: Use exceptions instead of error codes  
❌ **Ignore Finally**: Don't skip finally blocks  
❌ **Hide Errors**: Don't hide the original exception  
❌ **Silent Failures**: Don't fail silently  
❌ **Assume Valid Input**: Always validate input  

---

## 📞 Support and Resources

### Getting Help
- **Debugging**: Use logging and assertions
- **Testing**: Write comprehensive error tests
- **Documentation**: Document all error conditions
- **Code Review**: Peer review error handling

### Learning Resources
- **Effective Java**: Joshua Bloch - Chapter on error handling
- **Clean Code**: Robert Martin - Error handling principles
- **Java Documentation**: Exception handling best practices
- **Stack Overflow**: Search for specific error scenarios

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Auto-generated by*: Documentation Generator*" "Error handling strategies"

# docs/NAMING_CONVENTIONS.md
create_file "docs/NAMING_CONVENTIONS.md" "# Naming Conventions

> 📝 **Standard naming conventions for consistent, readable code in the DSA Java project**

---

## 🎯 Naming Philosophy

### Core Principles
- **Clarity**: Names should clearly indicate purpose
- **Consistency**: Use the same naming pattern throughout
- **Readability**: Names should be easy to read and pronounce
- **Conciseness**: Names should be brief but descriptive
- **Uniqueness**: Avoid name collisions

### Language Standards
- **Java Standards**: Follow Java naming conventions
- **English Language**: Use English words and abbreviations
- **Case Sensitivity**: Respect Java's case sensitivity rules
- **Reserved Words**: Avoid Java keywords and reserved words

---

## 📦 Package Naming

### Package Structure
```
com.dsa.algorithms.search     // Search algorithms
com.dsa.algorithms.sorting    // Sorting algorithms  
com.dsa.algorithms.datastructures // Data structures
com.dsa.utils                 // Utility classes
com.dsa.testing               // Test classes
```

### Naming Rules
- **Lowercase**: All package names in lowercase
- **Dots**: Use dots to separate package components
- **Descriptive**: Package names should be descriptive
- **Reverse Domain**: Use reversed domain name for unique packages
- **Single Words**: Use single words when possible

### Examples
```java
✅ com.dsa.algorithms.search
✅ com.dsa.utils.testing
✅ com.dsa.datastructures.linear

❌ com.dsa.Algorithms.Search
❌ com.dsa.algorithms.searchAlgorithms
❌ com.dsa.utils.Utils
```

---

## 📁 Class and Interface Naming

### Class Naming
```java
public class BinarySearch {           // PascalCase
public interface Searchable {          // PascalCase
public enum SortType {                // PascalCase
    QUICK_SORT,
    MERGE_SORT
}
```

### Naming Rules
- **PascalCase**: First letter of each word capitalized
- **Nouns**: Class names should be nouns
- **Descriptive**: Names should describe functionality
- **Singular**: Use singular for class names unless representing a collection

### Examples
```java
✅ public class LinkedList
✅ public class StackOperations  
✅ public class PriorityQueueManager
✅ public interface Searchable

❌ public class linkedList
❌ public class stackoperations
❌ public class priority_queue
❌ public class Manager
```

---

## 🔧 Method Naming

### Method Patterns
```java
public int findElement(int[] array, int target) {     // Verb + Noun
public void insertAtBeginning(int value) {          // Verb + Location
public boolean isEmpty() {                           // Boolean methods use is/has/can
public int getSize() {                               // Getter methods use get
public void setSize(int size) {                         // Setter methods use set
```

### Naming Rules
- **camelCase**: First word lowercase, subsequent words capitalized
- **Verbs**: Start with descriptive verbs
- **Descriptive**: Method names should describe what they do
- **Boolean Methods**: Use `is`, `has`, `can`, `should` prefixes
- **Getter Methods**: Use `get` prefix
- **Setter Methods**: Use `set` prefix

### Common Patterns
```java
// Boolean methods
public boolean isEmpty()
public boolean hasChildren()
public boolean canProcess()
public boolean shouldRetry()

// Getter methods
public int getSize()
public String getName()
public Object[] getData()

// Setter methods  
public void setSize(int size)
public void setName(String name)
public void setData(Object[] data)

// Action methods
public void insert(int value)
public void remove(int index)
public void clear()
public void reset()
```

---

## 📊 Variable Naming

### Instance Variables
```java
private int[] array;                    // camelCase, descriptive
private int size;                       // camelCase, simple
private boolean isEmpty;                 // camelCase, boolean
private String errorMessage;            // camelCase, descriptive
```

### Local Variables
```java
int index = 0;                         // camelCase, short names
String[] result = new String[10];        // camelCase, descriptive
boolean found = false;                  // camelCase, boolean
int temp = array[left];                  // camelCase, temporary
```

### Constants
```java
public static final int MAX_SIZE = 1000;    // UPPER_SNAKE_CASE
public static final String DEFAULT_NAME = "Default";
public static final double PI = 3.14159;
```

### Naming Rules
- **camelCase**: First word lowercase, subsequent words capitalized
- **Descriptive**: Names should indicate purpose
- **Short**: Use short names for local variables
- **Constants**: UPPER_SNAKE_CASE for final variables
- **Boolean**: Use descriptive boolean names

### Examples
```java
✅ private int[] dataArray;
✅ private int currentIndex;
✅ private boolean isInitialized;
✅ public static final int DEFAULT_CAPACITY = 10;

❌ private int[] arr;
❌ private int idx;
❌ private boolean flag;
❌ public static final int capacity = 10;
```

---

## 🏷️ Constants and Enums

### Constants
```java
public class Constants {
    public static final int MAX_SIZE = 1000;
    public static final String DEFAULT_ENCODING = "UTF-8";
    public static final double GOLDEN_RATIO = 1.618;
    public static final boolean DEBUG_MODE = false;
}
```

### Enums
```java
public enum SortType {
    BUBBLE_SORT,
    QUICK_SORT,
    MERGE_SORT,
    INSERTION_SORT
}

public enum QueueType {
    LINEAR_QUEUE,
    CIRCULAR_QUEUE,
    PRIORITY_QUEUE
}
```

### Naming Rules
- **UPPER_SNAKE_CASE**: All letters uppercase with underscores
- **Descriptive**: Names should be self-explanatory
- **Final**: Constants should be final
- **Enum Values**: Use UPPER_SNAKE_CASE for enum constants

---

## 📝 File Naming

### Source Files
```
BinarySearch.java              // PascalCase.java
LinkedListOperations.java      // PascalCase.java
SearchAlgorithmTest.java        // PascalCaseTest.java
```

### Test Files
```
BinarySearch_Test.java          // ClassName_Test.java
LinkedListOperations_Test.java // ClassName_Test.java
```

### Documentation Files
```
BinarySearch_Documentation.md   // ClassName_Documentation.md
BinarySearch_Test_Documentation.md // ClassName_Test_Documentation.md
```

### Naming Rules
- **PascalCase**: First letter of each word capitalized
- **Descriptive**: File names should indicate content
- **Test Suffix**: Test files end with `_Test`
- **Documentation Suffix**: Documentation files end with `_Documentation`

---

## 🔤 Interface and Abstract Classes

### Interfaces
```java
public interface Searchable {
    int search(int[] array, int target);
    boolean supports(int[] array);
}

public interface Sortable {
    void sort(int[] array);
    long getComparisons();
    long getSwaps();
}
```

### Abstract Classes
```java
public abstract class AbstractAlgorithm {
    protected int[] data;
    protected int size;
    
    public abstract void execute();
    
    public boolean isEmpty() {
        return size == 0;
    }
}
```

### Naming Rules
- **PascalCase**: Same as classes
- **Descriptive**: Names should indicate capability
- **Abstract**: Abstract classes should be prefixed with `Abstract`
- **Interfaces**: Use descriptive names ending in `-able` when appropriate

---

## 🧪 Test Naming

### Test Classes
```java
public class BinarySearchTest {           // ClassNameTest
public class LinkedListOperationsTest {   // ClassNameTest
public class AlgorithmPerformanceTest {    // FeatureTest
}
```

### Test Methods
```java
@Test
public void testBasicFunctionality() {    // test + Feature
@Test
public void testEdgeCases() {              // test + Feature
@Test  
public void testPerformance() {            // test + Feature
@Test
public void testNullInput() {              // test + Condition
```

### Naming Rules
- **Test Classes**: End with `Test` suffix
- **Test Methods**: Start with `test` prefix
- **Descriptive**: Method names should describe what's being tested
- **Conditions**: Include specific conditions in method names

### Test Categories
```java
// Functionality tests
testBasicFunctionality()
testEdgeCases()
testNormalCases()

// Performance tests
testPerformance()
testMemoryUsage()
testScalability()

// Error handling tests
testNullInput()
testInvalidInput()
testBoundaryConditions()
```

---

## 📚 Documentation Comments

### JavaDoc Comments
```java
/**
 * Binary search algorithm implementation.
 * 
 * <p>This class provides an efficient implementation of binary search
 * for sorted integer arrays. The algorithm runs in O(log n) time complexity
 * and O(1) space complexity.</p>
 * 
 * @author DSA Team
 * @version 1.0
 * @since 1.0
 * @see LinearSearch for alternative search algorithm
 */
```

### Method Comments
```java
/**
 * Searches for the target value in the sorted array.
 * 
 * @param array the sorted array to search in
 * @param target the value to search for
 * @return the index of the target, or -1 if not found
 * @throws IllegalArgumentException if array is null or not sorted
 * @see #isSorted(int[]) for sorting validation
 */
public int binarySearch(int[] array, int target) {
    // Implementation
}
```

### Inline Comments
```java
// Check if array is sorted (precondition for binary search)
if (!isSorted(array)) {
    throw new IllegalArgumentException("Array must be sorted");
}

// Calculate middle index to avoid overflow
int mid = left + (right - left) / 2;
```

---

## 🚫 Anti-Patterns

### Common Mistakes
```java
❌ // Abbreviations
int arr[];
List lst;
Map mp;

❌ // Single letters
int a, b, c;
String s;

❌ // Non-descriptive names
int temp;
int data;
Object obj;

❌ // Inconsistent casing
int arraySize;
int ArraySize;
int array_size;
```

### Correct Alternatives
```java
✅ // Descriptive names
int[] array;
List<String> list;
Map<String, Integer> map;

✅ // Meaningful names
int index, count, size;
String message;
Object result;

✅ // Consistent casing
int arraySize;
int listSize;
int mapSize;
```

---

## 📋 Naming Checklist

### Code Review Checklist
- [ ] Classes use PascalCase
- [ ] Methods use camelCase
- [ ] Constants use UPPER_SNAKE_CASE
- [ ] Variables are descriptive
- [ ] No abbreviations (except common ones)
- [ ] Boolean methods use is/has/can prefixes
- [ ] Getter/setter methods use get/set prefixes
- [ ] Test classes end with `Test` suffix
- [ ] Test methods start with `test` prefix

### File Organization Checklist
- [ ] File names match class names
- [ ] Test files follow naming convention
- [ ] Documentation files follow naming convention
- [ ] Package structure is logical
- [ ] No naming conflicts

---

## 🔧 Tools and Automation

### IDE Configuration
- **Code Templates**: Configure IDE templates for naming conventions
- **Code Inspection**: Set up rules for naming violations
- **Auto-Completion**: Configure to suggest correct naming
- **Refactoring**: Use IDE refactoring tools for renaming

### Build Tools
- **Checkstyle**: Configure naming rules in checkstyle.xml
- **PMD**: Set up naming convention rules
- **SonarQube**: Configure naming quality gates
- **SpotBugs**: Check for naming issues

### Automated Checks
```xml
<!-- checkstyle.xml -->
<module name="LocalVariableName">
    <property name="format" value="^[a-z][a-zA-Z0-9]*$"/>
</module>

<module name="MethodName">
    <property name="format" value="^[a-z][a-zA-Z0-9]*$"/>
</module>
```

---

## 📞 Support and Resources

### Learning Resources
- **Java Code Conventions**: Official Oracle documentation
- **Effective Java**: Joshua Bloch - Chapter on naming
- **Clean Code**: Robert Martin - Chapter on naming
- **Google Java Style Guide**: Comprehensive naming rules

### Tools
- **Checkstyle**: Code style checker
- **PMD**: Code quality checker
- **SonarLint**: IDE plugin for code quality
- **IntelliJ IDEA**: Built-in code inspection

### Community
- **Stack Overflow**: Search for naming questions
- **GitHub**: Review open-source projects
- **Java Forums**: Ask for naming advice
- **Code Review**: Peer review naming conventions

---

*📅 **Last Updated**: $(date '+%Y-%m-%d %H:%M:%S')*  
*🔧 **Auto-generated by*: Documentation Generator*" "Naming standards and conventions"
